alias nortonssh='ssh pi@192.168.0.101'
alias ipnb='cd /home/martin/owncloud/python/notebooks/ && ipython notebook'
alias a='alias'
alias llg='ll | grep'
alias hg='history | grep'
alias r='ranger'
alias m='w3mman'
alias nd='cd home/martin/owncloud/notes'
