alias nortonssh='ssh pi@192.168.0.101'
alias ipnb='cd $HOME/owncloud/python/notebooks/ && jupyter notebook'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -la'
alias a='alias'
alias llg='ll | grep'
alias hg='history | grep'
alias r='ranger'
alias m='w3mman'
